export type SafeArea = {
  top: number,
  right: number,
  bottom: number,
  left: number,
  width: number,
  height: number,
}

export type UserInfo = {
  nickName: string,
  avatarUrl?: string
}

type State = {
  lifeCycleNum: number
  statusBarHeight: number
  safeArea: SafeArea
  isDarkMode: boolean
  userInfo: UserInfo | null
}

export const state = reactive({
  lifeCycleNum: 0,
  statusBarHeight: 0,
  safeArea: {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: 0,
    height: 0,
  },
  isDarkMode: false,
  userInfo: null
} as State)

export const setLifeCycleNum = (num: number) => {
  state.lifeCycleNum = num
}

export const setStatusBarHeight = (height: number) => {
  state.statusBarHeight = height
}

export const setSafeArea = (value: SafeArea) => {
  state.safeArea = value
}

export const setUserInfo = (userInfo: UserInfo | null) => {
  state.userInfo = userInfo
}

export const checkSystemTheme = () => {
  // #ifdef WEB || MP-WEIXIN
  const info = uni.getAppBaseInfo();
  state.isDarkMode = info.hostTheme === 'dark';
  uni.onHostThemeChange((result) => {
    state.isDarkMode = result.hostTheme === 'dark';
  });
  // #endif
  // #ifdef APP
  uni.getSystemInfo({
    success: (res: GetSystemInfoResult) => {
      const appTheme = res.appTheme == "auto" ? (res.osTheme ?? 'light') : (res.appTheme ?? 'light')
      state.isDarkMode = appTheme == 'dark';
    }
  })
  uni.onAppThemeChange((res: AppThemeChangeResult) => {
    state.isDarkMode = (res.appTheme ?? 'light') == 'dark';
  })
  // #endif
}